# Generated by Django 5.2.8 on 2025-11-25 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('service', 'Church Service'), ('meeting', 'Meeting'), ('conference', 'Conference'), ('revival', 'Revival'), ('camp', 'Camp Meeting'), ('fellowship', 'Fellowship'), ('outreach', 'Outreach/Evangelism'), ('training', 'Training/Workshop'), ('celebration', 'Celebration/Anniversary'), ('holiday', 'Holiday'), ('other', 'Other')], default='service', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('none', 'One-time Event'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('scope', models.CharField(choices=[('mission', 'Mission-wide'), ('area', 'Area'), ('district', 'District'), ('branch', 'Branch')], default='mission', max_length=20)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('venue_address', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.area')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='YearlyCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('theme_verse', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yearly Calendar',
                'verbose_name_plural': 'Yearly Calendars',
                'ordering': ['-year'],
            },
        ),
    ]
