# Generated by Django 5.2.8 on 2025-11-26 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calendarevent_yearlycalendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pastor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'pastor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastored_branches', to=settings.AUTH_USER_MODEL),
        ),
    ]
