# Generated by Django 5.2.8 on 2025-11-26 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_pastor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_member_contribution_view',
            field=models.BooleanField(default=True, help_text='Allow members to view their contributions'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_member_profile_edit',
            field=models.BooleanField(default=True, help_text='Allow members to edit their profiles'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic database backups'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_frequency_days',
            field=models.IntegerField(default=7, help_text='Backup frequency in days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency_code',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='GH₵', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='data_retention_years',
            field=models.IntegerField(default=7, help_text='Years to retain historical data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_announcements',
            field=models.BooleanField(default=True, help_text='Enable announcements module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_attendance',
            field=models.BooleanField(default=True, help_text='Enable attendance tracking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_contributions',
            field=models.BooleanField(default=True, help_text='Enable contributions module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_csv_import',
            field=models.BooleanField(default=True, help_text='Enable CSV import functionality'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_expenditure',
            field=models.BooleanField(default=True, help_text='Enable expenditure module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_groups',
            field=models.BooleanField(default=True, help_text='Enable groups/ministries module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_offline_mode',
            field=models.BooleanField(default=True, help_text='Enable offline data caching'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_payroll',
            field=models.BooleanField(default=True, help_text='Enable payroll module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_push_notifications',
            field=models.BooleanField(default=False, help_text='Enable push notifications'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_reports',
            field=models.BooleanField(default=True, help_text='Enable reports module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sermons',
            field=models.BooleanField(default=True, help_text='Enable sermons module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False, help_text='Enable SMS notifications'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_two_factor_auth',
            field=models.BooleanField(default=False, help_text='Enable two-factor authentication'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fiscal_year_start_month',
            field=models.IntegerField(default=1, help_text='Month fiscal year starts (1-12)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lockout_duration_minutes',
            field=models.IntegerField(default=30, help_text='Account lockout duration in minutes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_allowed_ips',
            field=models.TextField(blank=True, help_text='Comma-separated IPs allowed during maintenance'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='System is under maintenance. Please check back later.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Put system in maintenance mode'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_login_attempts',
            field=models.IntegerField(default=5, help_text='Max failed login attempts before lockout'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#1e40af', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_strong_password',
            field=models.BooleanField(default=True, help_text='Require strong passwords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=60, help_text='Session timeout in minutes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='allow_pastor_announcements',
            field=models.BooleanField(default=True, help_text='Allow pastors to create announcements'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='allow_pastor_events',
            field=models.BooleanField(default=True, help_text='Allow pastors to create events'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_pwa',
            field=models.BooleanField(default=True, help_text='Enable Progressive Web App features'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_pastor_contribution_panel',
            field=models.BooleanField(default=False, help_text='Show contribution panel to pastors'),
        ),
    ]
