# Generated by Django 5.2.8 on 2025-11-27 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_allow_member_contribution_view_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('member_added', 'New Member'), ('contribution', 'Contribution'), ('expenditure', 'Expenditure'), ('announcement', 'Announcement'), ('remittance', 'Remittance'), ('commission', 'Commission'), ('payroll', 'Payroll'), ('attendance', 'Attendance'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('system', 'System'), ('prayer_request', 'Prayer Request'), ('visitor', 'Visitor')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('privacy', models.CharField(choices=[('public', 'Share with Church'), ('pastor_only', 'Pastor Only'), ('private', 'Private')], default='pastor_only', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prayed', 'Prayed For'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=15)),
                ('prayer_count', models.PositiveIntegerField(default=0)),
                ('answered_date', models.DateField(blank=True, null=True)),
                ('testimony', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prayer_requests', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prayer Request',
                'verbose_name_plural': 'Prayer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('first_visit_date', models.DateField()),
                ('how_heard', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New Visitor'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up Scheduled'), ('returned', 'Returned'), ('converted', 'Became Member'), ('declined', 'Not Interested')], default='new', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('converted_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visitors', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='core.branch')),
                ('converted_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_record', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_invited_visitors', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-first_visit_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitorFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('phone', 'Phone Call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('visit', 'Home Visit'), ('email', 'Email')], max_length=15)),
                ('notes', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('response', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('followed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.visitor')),
            ],
            options={
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='PrayerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.prayerrequest')),
            ],
            options={
                'unique_together': {('prayer_request', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SpecialDateReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding Anniversary'), ('baptism', 'Baptism Anniversary'), ('membership', 'Membership Anniversary')], max_length=15)),
                ('date', models.DateField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('notify_member', models.BooleanField(default=True)),
                ('notify_pastor', models.BooleanField(default=True)),
                ('notify_branch', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Special Date Reminder',
                'verbose_name_plural': 'Special Date Reminders',
                'unique_together': {('user', 'reminder_type')},
            },
        ),
    ]
