# Generated by Django 5.2.8 on 2025-11-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_prayerrequest_visitor_visitorfollowup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerrequest',
            name='privacy',
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prayer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Must be approved by pastor/admin before others can see'),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='visibility_scope',
            field=models.CharField(choices=[('branch', 'Branch Only'), ('district', 'District Wide'), ('area', 'Area Wide'), ('mission', 'Mission Wide')], default='branch', help_text='Who can see this prayer request', max_length=10),
        ),
    ]
