# Generated by Django 5.2.8 on 2025-11-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_prayerrequest_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#10b981', help_text='Accent color for highlights', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_banner',
            field=models.ImageField(blank=True, help_text='Dashboard banner image', null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_banner_url',
            field=models.URLField(blank=True, help_text='Fallback dashboard banner URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='© 2024 SDSCC. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_background',
            field=models.ImageField(blank=True, help_text='Login page background image', null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_background_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=1920', help_text='Fallback login background URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_color',
            field=models.CharField(default='#1e293b', help_text='Sidebar background color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon_url',
            field=models.URLField(blank=True, help_text='Fallback favicon URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_url',
            field=models.URLField(blank=True, help_text='Fallback logo URL if no upload'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Main site logo', null=True, upload_to='settings/'),
        ),
    ]
