# Generated by Django 5.2.8 on 2025-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_auditor_payroll_access',
            field=models.BooleanField(default=False, help_text='Allow auditors to access payroll dashboards for read-only oversight'),
        ),
    ]
