# Generated by Django 4.2.26 on 2025-11-29 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_sitesettings_allow_auditor_payroll_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('asset_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('equipment', 'Equipment'), ('building', 'Building'), ('other', 'Other')], max_length=20)),
                ('location_detail', models.CharField(blank=True, help_text='Specific location within branch', max_length=200)),
                ('value', models.DecimalField(decimal_places=2, help_text='Current value in GHS', max_digits=12)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase price', max_digits=12, null=True)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_assets', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Church Asset',
                'verbose_name_plural': 'Church Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchAssetTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_transfers', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='core.churchasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_transferred_from', to='core.branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_transferred_to', to='core.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Transfer',
                'verbose_name_plural': 'Asset Transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='ChurchAssetMaintenance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('upgrade', 'Upgrade'), ('cleaning', 'Cleaning')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Maintenance cost in GHS', max_digits=10, null=True)),
                ('performed_by', models.CharField(help_text='Who performed the maintenance', max_length=200)),
                ('performed_date', models.DateField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.churchasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance Records',
                'ordering': ['-performed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='churchasset',
            index=models.Index(fields=['branch', 'status'], name='core_church_branch__a10b94_idx'),
        ),
        migrations.AddIndex(
            model_name='churchasset',
            index=models.Index(fields=['category'], name='core_church_categor_cc5a46_idx'),
        ),
        migrations.AddIndex(
            model_name='churchasset',
            index=models.Index(fields=['asset_id'], name='core_church_asset_i_a9526a_idx'),
        ),
    ]
