# Generated by Django 4.2.26 on 2025-11-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_churchasset_churchassettransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_archives',
            field=models.BooleanField(default=True, help_text='Show archives in member sidebar'),
        ),
    ]
