# Generated by Django 4.2.26 on 2025-12-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_archive_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brancharchive',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='memberarchive',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.fiscalyear'),
        ),
    ]
