# Generated by Django 4.2.26 on 2025-12-30 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_sitesettings_show_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='color',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MissionFinancialSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance at start of month', max_digits=14)),
                ('total_remittances', models.DecimalField(decimal_places=2, default=0, help_text='Total remittances from branches', max_digits=14)),
                ('total_other_income', models.DecimalField(decimal_places=2, default=0, help_text='Other mission income', max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total income for month', max_digits=14)),
                ('total_payroll', models.DecimalField(decimal_places=2, default=0, help_text='Total staff payroll', max_digits=14)),
                ('total_mission_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Total mission-level expenses', max_digits=14)),
                ('total_mission_returns', models.DecimalField(decimal_places=2, default=0, help_text='Money returned to branches', max_digits=14)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, help_text='Total expenditure for month', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, help_text='Closing balance at end of month', max_digits=14)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_mission_summaries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_summaries', to='core.fiscalyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission Financial Summary',
                'verbose_name_plural': 'Mission Financial Summaries',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BranchFinancialSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance at start of month', max_digits=14)),
                ('total_tithe', models.DecimalField(decimal_places=2, default=0, help_text='Total tithe collected', max_digits=14)),
                ('total_offerings', models.DecimalField(decimal_places=2, default=0, help_text='Total offerings collected', max_digits=14)),
                ('total_other_contributions', models.DecimalField(decimal_places=2, default=0, help_text='Other contributions', max_digits=14)),
                ('mission_returns', models.DecimalField(decimal_places=2, default=0, help_text='Money received from mission', max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total income for month', max_digits=14)),
                ('total_branch_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Branch-level expenses', max_digits=14)),
                ('remittance_to_mission', models.DecimalField(decimal_places=2, default=0, help_text='Amount remitted to mission', max_digits=14)),
                ('pastor_commission', models.DecimalField(decimal_places=2, default=0, help_text='Pastor commission paid', max_digits=14)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, help_text='Total expenditure for month', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, help_text='Closing balance at end of month', max_digits=14)),
                ('tithe_target', models.DecimalField(decimal_places=2, default=0, help_text='Monthly tithe target', max_digits=12)),
                ('target_achieved', models.BooleanField(default=False)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of target achieved', max_digits=5)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_summaries', to='core.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_branch_summaries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_summaries', to='core.fiscalyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Financial Summary',
                'verbose_name_plural': 'Branch Financial Summaries',
                'ordering': ['-year', '-month', 'branch__name'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
    ]
