# Generated by Django 4.2.27 on 2026-01-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_brancharchive_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
    ]
