# Generated by Django 4.2.27 on 2026-01-01 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0004_make_all_fiscal_year_nullable'),
        ('expenditure', '0003_make_fiscal_year_nullable'),
        ('core', '0012_calendarevent_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('cash', 'Cash (Physically Held)'), ('receivable', 'Receivable (Owed to Owner)'), ('payable', 'Payable (Owed by Owner)')], max_length=20)),
                ('owner_type', models.CharField(choices=[('mission', 'Mission (National)'), ('area', 'Area'), ('district', 'District'), ('branch', 'Branch'), ('member', 'Member')], max_length=20)),
                ('counterparty_type', models.CharField(blank=True, choices=[('mission', 'Mission (National)'), ('area', 'Area'), ('district', 'District'), ('branch', 'Branch'), ('member', 'Member')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_type', models.CharField(choices=[('contribution', 'Contribution'), ('expenditure', 'Expenditure'), ('remittance', 'Remittance'), ('commission', 'Commission'), ('external_income', 'External Income'), ('adjustment', 'Manual Adjustment'), ('opening_balance', 'Opening Balance')], max_length=20)),
                ('entry_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed'), ('cleared', 'Cleared')], default='active', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='contributions.tithecommission')),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='contributions.contribution')),
                ('counterparty_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_counterparty', to='core.area')),
                ('counterparty_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_counterparty', to='core.branch')),
                ('counterparty_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_counterparty', to='core.district')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('expenditure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='expenditure.expenditure')),
                ('owner_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_owned', to='core.area')),
                ('owner_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_owned', to='core.branch')),
                ('owner_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_owned', to='core.district')),
                ('owner_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_owned', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='contributions.remittance')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='core.ledgerentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['owner_type', 'entry_type', 'entry_date'], name='core_ledger_owner_t_f3361a_idx'), models.Index(fields=['owner_branch', 'entry_type'], name='core_ledger_owner_b_8cfd38_idx'), models.Index(fields=['entry_date', 'source_type'], name='core_ledger_entry_d_1181c7_idx'), models.Index(fields=['status'], name='core_ledger_status_f7d8bb_idx')],
            },
        ),
    ]
