# Generated by Django 4.2.27 on 2026-01-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_calendarevent_color'),
        ('contributions', '0002_missionreturnsperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='core.fiscalyear'),
        ),
    ]
