# Generated by Django 4.2.27 on 2026-01-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_calendarevent_color'),
        ('contributions', '0003_make_fiscal_year_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='core.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='tithecommission',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='core.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='weeklycontributionsummary',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_summaries', to='core.fiscalyear'),
        ),
    ]
