# Generated by Django 4.2.27 on 2026-01-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_make_all_fiscal_year_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='draft_expires_at',
            field=models.DateTimeField(blank=True, help_text='When draft auto-submits', null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft contributions can be edited within 24 hours'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When draft was finalized', null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', max_length=20),
        ),
    ]
