# Generated by Django 4.2.27 on 2026-01-01 23:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0005_add_draft_mode_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionDonation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('donation_type', models.CharField(choices=[('general', 'General Donation'), ('project', 'Special Project'), ('building', 'Building Fund'), ('missions', 'Missions & Outreach'), ('education', 'Education Fund'), ('welfare', 'Welfare Fund'), ('other', 'Other')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='mission_donation_receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor name in public reports')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_donations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_mission_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission Donation',
                'verbose_name_plural': 'Mission Donations',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
