# Generated by Django 4.2.27 on 2026-01-02 13:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ledger_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0006_add_mission_donation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributiontype',
            name='scope',
            field=models.CharField(choices=[('mission', 'Mission (National)'), ('area', 'Area'), ('district', 'District'), ('branch', 'Branch')], default='mission', help_text='Defines the hierarchical level this contribution type belongs to', max_length=20),
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('branch', 'Branch'), ('mission', 'Mission')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(help_text='Date the opening balance was recorded')),
                ('description', models.TextField(default='Opening Balance – Pre-System Funds', help_text='Description of the opening balance')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('documentation', models.FileField(blank=True, help_text='Supporting documentation for the opening balance', null=True, upload_to='opening_balance_docs/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opening_balances', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='core.branch')),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='contributions.contributiontype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opening Balance',
                'verbose_name_plural': 'Opening Balances',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HierarchyTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_level', models.CharField(choices=[('mission', 'Mission'), ('area', 'Area'), ('district', 'District'), ('branch', 'Branch')], max_length=20)),
                ('destination_level', models.CharField(choices=[('mission', 'Mission'), ('area', 'Area'), ('district', 'District'), ('branch', 'Branch')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('allocation', 'Regular Fund Allocation'), ('special_project', 'Special Project Funding'), ('emergency', 'Emergency Support'), ('operations', 'Operational Support'), ('other', 'Other')], default='allocation', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('documentation', models.FileField(blank=True, help_text='Supporting documentation for the transfer', null=True, upload_to='hierarchy_transfers/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='core.area')),
                ('destination_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='core.branch')),
                ('destination_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='core.district')),
                ('source_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='core.area')),
                ('source_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='core.branch')),
                ('source_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='core.district')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hierarchy Transfer',
                'verbose_name_plural': 'Hierarchy Transfers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HierarchyRemittance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_level', models.CharField(choices=[('area', 'Area'), ('district', 'District')], max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_sent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='hierarchy_remittance_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('verified', 'Verified (Paid)'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='core.area')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hierarchy_remittances', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='core.district')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hierarchy_remittances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hierarchy Remittance',
                'verbose_name_plural': 'Hierarchy Remittances',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('contribution_type',), name='unique_mission_contribution_type'),
        ),
        migrations.AlterUniqueTogether(
            name='openingbalance',
            unique_together={('branch', 'contribution_type')},
        ),
        migrations.AlterUniqueTogether(
            name='hierarchyremittance',
            unique_together={('branch', 'destination_level', 'district', 'month', 'year'), ('branch', 'destination_level', 'area', 'month', 'year')},
        ),
    ]
