# Generated by Django 4.2.26 on 2025-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifies_for_salary',
            field=models.BooleanField(default=False, help_text='Whether this user qualifies for salary payments'),
        ),
    ]
