# Generated by Django 4.2.26 on 2025-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_base_salary_user_qualifies_for_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='baptism_by',
            field=models.CharField(blank=True, help_text='Name of minister who performed baptism', max_length=100),
        ),
    ]
