# Generated by Django 4.2.26 on 2025-11-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_baptism_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ordaining_minister',
            field=models.CharField(blank=True, help_text='Name of minister who performed ordination', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='ordination_date',
            field=models.DateField(blank=True, help_text='Date of ordination into ministry', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ordination_place',
            field=models.CharField(blank=True, help_text='Church/location where ordination took place', max_length=200),
        ),
    ]
