# Generated by Django 4.2.26 on 2025-11-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_pastor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pastoral_rank',
            field=models.CharField(choices=[('none', 'None'), ('associate', 'Associate Pastor'), ('branch', 'Branch Pastor'), ('senior', 'Senior Pastor'), ('district', 'District Pastor'), ('area', 'Area Pastor'), ('mission', 'Mission Pastor'), ('overseer', 'General Overseer')], default='none', max_length=20),
        ),
    ]
