# Generated by Django 4.2.26 on 2025-12-30 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_make_email_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('other_names', 'Other Names'), ('email', 'Email'), ('phone', 'Phone Number'), ('date_of_birth', 'Date of Birth'), ('gender', 'Gender'), ('address', 'Address'), ('city', 'City'), ('region', 'Region'), ('marital_status', 'Marital Status'), ('profession', 'Profession'), ('employer', 'Employer'), ('emergency_contact_name', 'Emergency Contact Name'), ('emergency_contact_phone', 'Emergency Contact Phone'), ('emergency_contact_relationship', 'Emergency Contact Relationship')], max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Current value')),
                ('new_value', models.TextField(help_text='Requested new value')),
                ('reason', models.TextField(blank=True, help_text='Reason for change')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Change Request',
                'verbose_name_plural': 'User Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
