# Generated by Django 5.2.8 on 2025-11-27 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_sitesettings_accent_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_services', models.IntegerField(default=0, help_text='Number of services held in the month')),
                ('average_attendance', models.DecimalField(decimal_places=2, default=0, help_text='Average attendance per service', max_digits=8)),
                ('total_attendance', models.IntegerField(default=0, help_text='Total attendance for all services')),
                ('visitors_count', models.IntegerField(default=0, help_text='Number of visitors')),
                ('new_members', models.IntegerField(default=0, help_text='New members added')),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, help_text='Total contributions for the month', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tithe_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tithe collected', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('offering_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total offering collected', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('special_contributions', models.DecimalField(decimal_places=2, default=0, help_text='Special contributions (building, projects, etc.)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, help_text='Total expenditure for the month', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('utility_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Utility bills (electricity, water, etc.)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maintenance_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Building maintenance and repairs', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Other operational expenses', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mission_remittance_due', models.DecimalField(decimal_places=2, default=0, help_text='Amount due to mission (tithe portion)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mission_remittance_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to mission', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mission_remittance_balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance remaining to be paid', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('branch_balance', models.DecimalField(decimal_places=2, default=0, help_text='Remaining funds in branch account', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved by Mission'), ('paid', 'Mission Remittance Paid'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date mission remittance was paid', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (bank, mobile money, etc.)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('attachment', models.FileField(blank=True, help_text='Supporting documents (PDF, Excel, etc.)', null=True, upload_to='monthly_reports/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports', to='core.fiscalyear')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-year', '-month', 'branch__name'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('contribution', 'Contribution'), ('expenditure', 'Expenditure')], max_length=20)),
                ('item_type', models.CharField(help_text='e.g., Tithe, Offering, Electricity, Water', max_length=100)),
                ('description', models.CharField(help_text='Description of the item', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.IntegerField(default=1, help_text='Number of occurrences (e.g., weeks, units)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_items', to='reports.monthlyreport')),
            ],
            options={
                'verbose_name': 'Report Item',
                'verbose_name_plural': 'Report Items',
                'ordering': ['category', 'item_type'],
            },
        ),
    ]
