# Generated by Django 4.2.27 on 2026-01-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ledger_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictFinancialReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance at start of month', max_digits=14)),
                ('contributions_received', models.DecimalField(decimal_places=2, default=0, help_text='District-scoped contributions received', max_digits=14)),
                ('remittances_received', models.DecimalField(decimal_places=2, default=0, help_text='Remittances received from branches', max_digits=14)),
                ('transfers_received', models.DecimalField(decimal_places=2, default=0, help_text='Transfers received from Area or other levels', max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total income for the month', max_digits=14)),
                ('expenditures', models.DecimalField(decimal_places=2, default=0, help_text='District expenditures', max_digits=14)),
                ('transfers_sent', models.DecimalField(decimal_places=2, default=0, help_text='Transfers sent to other levels', max_digits=14)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, help_text='Total expenditure for the month', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, help_text='Closing balance at end of month', max_digits=14)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('report_data', models.JSONField(default=dict, help_text='Detailed report data')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_reports', to='core.district')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_district_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'District Financial Report',
                'verbose_name_plural': 'District Financial Reports',
                'ordering': ['-year', '-month', 'district__name'],
                'unique_together': {('district', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AreaFinancialReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance at start of month', max_digits=14)),
                ('contributions_received', models.DecimalField(decimal_places=2, default=0, help_text='Area-scoped contributions received', max_digits=14)),
                ('remittances_received', models.DecimalField(decimal_places=2, default=0, help_text='Remittances received from branches', max_digits=14)),
                ('transfers_received', models.DecimalField(decimal_places=2, default=0, help_text='Transfers received from Mission or other levels', max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total income for the month', max_digits=14)),
                ('expenditures', models.DecimalField(decimal_places=2, default=0, help_text='Area expenditures', max_digits=14)),
                ('transfers_sent', models.DecimalField(decimal_places=2, default=0, help_text='Transfers sent to other levels', max_digits=14)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, help_text='Total expenditure for the month', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, help_text='Closing balance at end of month', max_digits=14)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('report_data', models.JSONField(default=dict, help_text='Detailed report data')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_reports', to='core.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_area_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area Financial Report',
                'verbose_name_plural': 'Area Financial Reports',
                'ordering': ['-year', '-month', 'area__name'],
                'unique_together': {('area', 'month', 'year')},
            },
        ),
    ]
