# Generated by Django 4.2.27 on 2026-01-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='tithe_deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of gross salary for tithe deduction', max_digits=5),
        ),
    ]
