# Generated by Django 4.2.27 on 2026-01-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ledger_entry'),
        ('payroll', '0002_add_tithe_deduction_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='core.fiscalyear'),
        ),
    ]
