# Generated by Django 4.2.26 on 2025-12-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment ID or transaction reference', max_length=100),
        ),
    ]
