# Generated by Django 4.2.27 on 2026-01-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_calendarevent_color'),
        ('expenditure', '0002_expenditure_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='core.fiscalyear'),
        ),
    ]
