# Generated by Django 4.2.27 on 2026-01-01 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ledger_entry'),
        ('expenditure', '0003_make_fiscal_year_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitybill',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_bills', to='core.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='welfarepayment',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_payments', to='core.fiscalyear'),
        ),
    ]
