# Generated by Django 4.2.27 on 2026-01-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_alter_contributiontype_scope_openingbalance_and_more'),
        ('expenditure', '0004_make_fiscal_year_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='contribution_type',
            field=models.ForeignKey(blank=True, help_text='Fund/contribution type this expenditure is charged against', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='contributions.contributiontype'),
        ),
    ]
