# Generated by Django 4.2.27 on 2025-12-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(help_text='Start date of the week (Monday)')),
                ('week_end_date', models.DateField(help_text='End date of the week (Sunday)')),
                ('total_attendees', models.IntegerField(default=0, help_text='Total unique attendees for the week')),
                ('total_members', models.IntegerField(default=0, help_text='Total active members in the system')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of members who attended', max_digits=5)),
                ('sabbath_attendance', models.IntegerField(default=0)),
                ('midweek_attendance', models.IntegerField(default=0)),
                ('special_service_attendance', models.IntegerField(default=0)),
                ('first_time_visitors', models.IntegerField(default=0)),
                ('average_per_service', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Attendance',
                'verbose_name_plural': 'Weekly Attendances',
                'ordering': ['-week_start_date'],
                'unique_together': {('week_start_date', 'week_end_date')},
            },
        ),
    ]
