# Generated by Django 4.2.27 on 2026-01-01 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_ledger_entry'),
        ('attendance', '0002_weeklyattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True)),
                ('scope', models.CharField(choices=[('mission', 'Mission-Wide'), ('area', 'Area'), ('district', 'District'), ('branch', 'Branch'), ('custom', 'Custom Selection')], default='branch', max_length=20)),
                ('meeting_type', models.CharField(choices=[('general', 'General Meeting'), ('board', 'Board Meeting'), ('staff', 'Staff Meeting'), ('executive', 'Executive Meeting'), ('training', 'Training Session'), ('prayer', 'Prayer Meeting'), ('other', 'Other')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_hours_before', models.IntegerField(default=24)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('attendance_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.area')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.district')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='invited', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff_member', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_meeting_attendances', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='attendance.meeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Attendee',
                'verbose_name_plural': 'Meeting Attendees',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
