# Generated by Django 4.2.27 on 2026-01-02 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_add_meeting_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionStaffAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the staff meeting/attendance')),
                ('title', models.CharField(default='Mission Staff Meeting', help_text='Optional custom title for this attendance session', max_length=200)),
                ('is_locked', models.BooleanField(default=False, help_text='Attendance is locked after 24 hours')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('total_staff', models.IntegerField(default=0, help_text='Total mission staff members')),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Meeting notes or agenda')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_attendances', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_staff_attendances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission Staff Attendance',
                'verbose_name_plural': 'Mission Staff Attendances',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='MissionStaffAttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.missionstaffattendance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_staff_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission Staff Attendance Record',
                'verbose_name_plural': 'Mission Staff Attendance Records',
                'ordering': ['staff_member__first_name', 'staff_member__last_name'],
                'unique_together': {('attendance', 'staff_member')},
            },
        ),
    ]
